excluded:
  - Pods
identifier_name:
  excluded:
    - on
    - off
line_length: 150
disabled_rules:
  - force_cast
opt_in_rules:
  - array_init
  - implicitly_unwrapped_optional
  - number_separator
  - unused_import
  - sorted_imports
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - anyobject_protocol
  - convenience_type
  - empty_string
  - file_name
  - first_where
  - modifier_order
  - toggle_bool
  - unused_declaration
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - closure_spacing
  - closure_body_length
  - closure_end_indentation
  - force_try
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_enum_raw_value
  - explicit_init
  - fatal_error_message
  - file_header
  - function_default_parameter_at_end
  - implicit_return
  - literal_expression_end_indentation
  - multiline_function_chains
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - quick_discouraged_call
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - static_operator
  - strong_iboutlet
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
#  - let_var_whitespace       https://github.com/realm/SwiftLint/issues/2980 - false positive with Swift 5.1 property wrappers
file_length:
  warning: 500
  error: 800
reporter: "xcode"
