name: deflaking-on-github

on:
  push:
    branches:
      - deflake-ui-tests  # debug this workflow
  schedule:
     # At 30 min past every hour between 8 pm and 7 am PST on weekday
    - cron:  '30 3-14 * * 1-5' # https://crontab.guru/#30_3-14_*_*_1-5
     # Every 30 min on weekend
    - cron:  '*/30 * * * 0,6'  # https://crontab.guru/#*/30_*_*_*_0,6

jobs:
  test-continously:

    runs-on: macos-latest
    timeout-minutes: 45
    env:
      NSUnbufferedIO: YES

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Prepare github runner
      run: bin/github/prepare-runner-for-ui-tests.sh
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: bundled-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: deflake UI Tests
      env:
        SUBMIT_METRICS_URL: ${{ secrets.SUBMIT_METRICS_URL }}
        TIME_LIMIT_MINUTES: 25 
      run: |
        bin/dev/deflake-ui-tests.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp /tmp/events-detected-during-ui-tests.txt . || true
        zip -r results.zip test-results/ui-tests-latest.xcresult || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: events-detected-during-ui-tests.txt
        path: events-detected-during-ui-tests.txt
        if-no-files-found: ignore
