name: release-on-github

on:
  push:
    branches: [ pz/experiment/create-pre-release ]
    tags: 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2.3.1
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@master
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: SpartaConnect
        action: build
        configuration: Release
        derived-data-path: build/derived
    - name: Archive
      run: |
        bundle exec ./bin/xc-scheme.sh SpartaConnect -configuration Release -derivedDataPath build/derived -archivePath build/archive archive
        ls -la build/
        cd build
        zip -r archive.zip archive.xcarchive
    - name: Upload archive results
      uses: actions/upload-artifact@v2
      with:
        path: build/archive.zip
