name: release-on-github

on:
push:
  tags:
  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2.3.1
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: SpartaConnect
        action: build
        configuration: Release
        derived-data-path: derived
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rare-test-events.plist
        path: rare-test-events.plist
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      if: always()  # Setup credentials even if the workflow failed
    - name: Log Build
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()  # Need to run to log the workflow failure
