name: release-on-github

on:
  push:
    branches: [ pz/experiment/create-pre-release ]
    tags: 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: Build and Release
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2.3.1
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby version
      run: ruby --version
    - name: bundle
      run: |
        gem install bundler
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@master
      with:
        workspace: SpartaConnect.xcworkspace
        scheme: SpartaConnect
        action: build
        configuration: Release
        derived-data-path: build/derived
    - name: Archive
      run: |
        bundle exec ./bin/xc-scheme.sh SpartaConnect -configuration Release -derivedDataPath build/derived -archivePath build/archive archive
        ls -la build/
        pushd build # refactor use ditto
        zip --recurse-paths --symlinks archive.zip archive.xcarchive
        popd
    - name: Upload archive results
      uses: actions/upload-artifact@v2
      with:
        name: archive.xcarchive
        path: build/archive.zip
    - name: Notarize the App
      env:
        DEVELOPER_ID_LOGIN: ${{ secrets.DEVELOPER_ID_LOGIN }}
        DEVELOPER_ID_PASSWORD: ${{ secrets.DEVELOPER_ID_PASSWORD }}
      run: bin/dev/notarize.sh
    - name: Upload Notarized app
      uses: actions/upload-artifact@v2
      with:
        name: SpartaConnect
        path: build/export/SpartaConnect.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automatically Created Release
          - Please update and upload appcast.xml (visible to customers)
          - Update these release notes (only visible to developers)
        draft: true
        prerelease: true
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/export/SpartaConnect.zip
        asset_name: SpartaConnect.zip
        asset_content_type: application/zip
